### ISSUE TITLE
Write a post for Rackspace DevOps Blog

### ISSUE THREAD

**Issue by troyswanson** [mattr-/hubot-rackspace-dns#1]
Gentlemen. We've got a little developer blog here at Rackspace that @jnoller maintains. If you're down, we'd love to have you write a post about this Hubot plugin. Idea for article outline:
1. Describe the issue you had to deal with,
2. the idea to use Hubot,
3. the development of the plugin,
4. and how it's helped.

The entire [dev site](http://developer.rackspace.com/) is Jekyll-based, which is awesome, and the source for which is publicly available on GitHub via [rackerlabs/devsite](https://github.com/rackerlabs/devsite).

What do you think?

**Comment by parkr** [comment]
I'd love to collaborate on a post. Thanks for coming up with this idea, @troyswanson!

We'll need to develop the plugin and test how it's helped (I personally use Rackspace for most of my DNS needs, so this will probably be mostly me), but once that's done, I'd love to see it posted to the Rackspace website.

**Comment by troyswanson** [comment]
Sounds good. Obviously take your time. Thanks for being receptive to the idea :smile:

**Comment by troyswanson** [comment]
Closing this since it's forever old. Hope all is well with you guys.
