### ISSUE TITLE
Dat Travis

### ISSUE THREAD

**Issue by parkr** [mattr-/hubot-rackspace-dns#3]
Ready to write tests for this guy. Would you please connect travis to this repo? :smiley:

**Comment by mattr-** [comment]
I think you should be able to do it. You have push access to this repo. :smiley:

**Comment by parkr** [comment]
I wish! I would need "Admin" privileges, which you can't give someone else on a private repo.

**Comment by mattr-** [comment]
Lame. Ok. You'll have to give me a few more days to set it up.

**Comment by mattr-** [comment]
And then everybody in my whole entire family goes and gets sick :boom: 17 days later, I finally do it.

https://travis-ci.org/mattr-/hubot-rackspace-dns
